name: "Github Action to OTLP"
description: "Record job information as trace and transmit via OTLP"
inputs:
  endpoint:
    description: "Endpoint to send OTLP to"
    required: true
  headers:
    description: "Headers to configure gRPC metadata"
    required: false
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
